# Generated by Django 4.0.6 on 2022-07-30 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения опроса')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='choices',
            field=models.ManyToManyField(related_name='polls', through='webapp.Answer', to='webapp.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch0ices', to='webapp.poll', verbose_name='Опрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p0ll', to='webapp.choice', verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ch0ice', to='webapp.poll', verbose_name='Опрос'),
        ),
    ]
